apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3

  storage:
    size: 20Gi

  monitoring:
    enabled: true

  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: appuser-secret
