apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.26 # Use a specific chart version
    chart: cloudnative-pg
    helm:
      values: |
        # Add any specific CloudNativePG Helm values here
        # For example:
        # postgresql:
        #   image: quay.io/cloudnative-pg/postgresql:15.5
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
