apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 2

  storage:
    size: 20Gi

  monitoring:
    enablePodMonitor: true
  
  backup:
    barmanObjectStore:
      destinationPath: gs://k8s-pg-backup
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
      wal:
        compression: gzip

  
  managed:
    roles:
    - name: example
      createdb: true
      ensure: present
      login: true
      superuser: false
      inRoles:
        - pg_monitor
        - pg_signal_backend
      passwordSecret:
        name: example-user-secret
