apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 2

  storage:
    size: 20Gi

  monitoring:
    enablePodMonitor: true

  superuserSecret:
    name: superuser-secret
    
  managed:
    roles:
    - name: example
      createdb: true
      ensure: present
      login: true
      superuser: false
      inRoles:
        - pg_monitor
        - pg_signal_backend
      passwordSecret:
        name: example-user-secret